"""Step catalog Markdown formatter for Behave.

Register in ``behave.ini``::

    [behave.formatters]
    stepcatalog = behave_modern_md_report.step_catalog_formatter:StepCatalogMarkdownFormatter

Then run::

    behave -f stepcatalog -o step_catalog.md

The formatter performs static analysis of the ``features/steps`` directory
and produces a Markdown document with all step definitions, their patterns,
parameters, docstrings, source code, and aggregate statistics.
"""

from __future__ import annotations

import contextlib
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

try:
    from behave.formatter.base import Formatter
except Exception:  # pragma: no cover - Behave optional at import time
    Formatter = object

from .markdown import MarkdownBuilder
from .step_scanner import StepCatalog, StepDefinition, scan_directory


class StepCatalogMarkdownFormatter(Formatter):  # type: ignore[misc]
    """Behave formatter that produces a step definition catalog in Markdown."""

    name = "stepcatalog"
    description = "Step definition catalog in Markdown (static analysis)"

    def __init__(self, stream_opener: Any, config: Any) -> None:
        super().__init__(stream_opener, config)

        userdata = getattr(config, "userdata", {}) or {}
        self._title = userdata.get("bmr.title", "Step Catalog")
        self._steps_dir = userdata.get("bmr.steps_dir", "features/steps")

        self._stream_opener = stream_opener
        self._config = config

    def _find_steps_dir(self) -> Path:
        base = Path(getattr(self._config, "base_dir", ".") or ".")
        candidates = [
            base / self._steps_dir,
            Path(self._steps_dir),
            base / "features" / "steps",
        ]
        for c in candidates:
            if c.is_dir():
                return Path(c).resolve()
        return Path(candidates[0]).resolve()

    def close(self) -> None:
        steps_dir = self._find_steps_dir()
        catalog = scan_directory(steps_dir)
        markdown = render_step_catalog(catalog, title=self._title)

        output_path = self._resolve_output_path()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(markdown, encoding="utf-8")
        with contextlib.suppress(Exception):  # pragma: no cover
            sys.stdout.write(f"\nStep catalog written to: {output_path}\n")

    def _resolve_output_path(self) -> Path:
        candidate = getattr(self._stream_opener, "name", None) or getattr(self._stream_opener, "filename", None)
        if candidate:
            return Path(candidate)
        outputs = getattr(self._config, "outputs", None) or []
        for output in outputs:
            name = getattr(output, "name", None)
            if name and name not in ("<stdout>", "<stderr>"):
                return Path(name)
        return Path("step-catalog.md")


def render_step_catalog(
    catalog: StepCatalog,
    title: str = "Step Catalog",
) -> str:
    """Render a step catalog into a Markdown document.

    Args:
        catalog: The step catalog to render.
        title: Document title.

    Returns:
        Markdown string.

    """
    md = MarkdownBuilder()
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # --- Title ---
    md.heading(1, f"📋 {title}")
    md.paragraph(f"**Generated:** {now}")
    md.paragraph(
        f"{catalog.total} step definitions across {len(catalog.by_file)} files"
        + f" · {', '.join(f'{k.capitalize()} {v}' for k, v in sorted(catalog.by_keyword.items()))}"
    )

    md.horizontal_rule()

    # --- Statistics ---
    md.heading(2, "Statistics")
    md.table(
        ["Metric", "Value"],
        [
            ["Total steps", str(catalog.total)],
            ["Files", str(len(catalog.by_file))],
            ["Parameterised", str(catalog.with_params)],
            ["With docstring", str(catalog.with_docstring)],
            ["Regex patterns", str(catalog.regex_steps)],
        ],
    )

    # --- Steps by keyword ---
    md.heading(2, "Steps by Keyword")
    keyword_rows = [[k.capitalize(), str(v)] for k, v in sorted(catalog.by_keyword.items())]
    md.table(["Keyword", "Count"], keyword_rows)

    # --- Steps by file ---
    md.heading(2, "Steps by File")
    file_rows = [[f, str(v)] for f, v in sorted(catalog.by_file.items())]
    md.table(["File", "Count"], file_rows)

    md.horizontal_rule()

    # --- Step details ---
    md.heading(2, "Step Definitions")

    for step in catalog.steps:
        _render_step_detail(md, step)

    md.horizontal_rule()

    # --- Footer ---
    md.paragraph(f"*Generated by Behave Markdown Report on {now}.*")

    return md.join()


def _render_step_detail(md: MarkdownBuilder, step: StepDefinition) -> None:
    """Render a single step definition as a collapsible details block."""
    keyword_icon = {
        "given": "🔵",
        "when": "🟡",
        "then": "🟢",
        "step": "⚪",
    }.get(step.keyword, "⚪")

    pattern_display = step.pattern or "(no pattern)"
    summary = f"{keyword_icon} {step.keyword.capitalize()}: {pattern_display} — `{step.func_name}`"

    content = MarkdownBuilder()

    content.heading(4, "Location")
    content.paragraph(f"`{step.file_path}:{step.line}`")

    if step.params:
        content.heading(4, "Parameters")
        content.bullet([f"`{p}`" for p in step.params])

    if step.docstring:
        content.heading(4, "Description")
        content.blockquote(step.docstring)

    content.heading(4, "Source")
    lang = "python"
    content.code_block(step.source, lang)

    if step.is_regex:
        content.paragraph("**Pattern type:** Regex (compiled)")

    md.details(summary=summary, content_lines=content.lines, open_=False)
